services:
  - type: web
    name: budgetapp
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: postgres://budgetapp:nQhInEKyuavaqDcIqB4WdOaR8wXZyiug@dpg-chkjs2m4dadfmsmblf0g-a/budgetapp_t6pb
        fromDatabase:
          name: budgetapp
          property: connectionString
      - key: BUDGET_APP_DATABASE_PASSWORD
        sync: false

databases:
  - name: budgetapp
    databaseName: budgetapp
    user: budgetapp

