databases:
  - name: postgresql
    databaseName: Budget_app
    user: budget

services:
  - type: web
    name: Budget_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  postgresql
          property: connectionString
      - key: config/master.key
        sync: false