services:
  - type: web
    name: budget_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: BUDGET_APP_DATABASE_PASSWORD
        sync: false

databases:
  - name: postgresql
    databaseName: budget_app
    user: budget_app

